spring:
  datasource:
    url: jdbc:mysql://localhost:3306/m_blog
    username: root
    password: wzw006
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      # 配置swagger3需要以下配置
      matching-strategy: ant_path_matcher
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
oss:
  qiniu:
    domain-url: http://ri1bzqp09.bkt.clouddn.com/
    access-key: IzTywocCdtTl4ASlp5WRNDf4jPEDIESEy0W-NM53
    secret-key: cRTwVGhCWgHU4nipm-1sSMmgK9aksMWYxQuPn-OD
    bucket: moondust